package com.siraj.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (Techno-Spiritual)
val md_theme_light_primary = Color(0xFF155C4A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCBE8DC)
val md_theme_light_onPrimaryContainer = Color(0xFF072019)
val md_theme_light_secondary = Color(0xFFA87824)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDFA6)
val md_theme_light_onSecondaryContainer = Color(0xFF261900)
val md_theme_light_tertiary = Color(0xFF147A70)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB1ECE2)
val md_theme_light_onTertiaryContainer = Color(0xFF00201D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7F8F5)
val md_theme_light_onBackground = Color(0xFF17211D)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF17211D)
val md_theme_light_surfaceVariant = Color(0xFFE7EFEB)
val md_theme_light_onSurfaceVariant = Color(0xFF52635C)
val md_theme_light_outline = Color(0xFF52635C)

// Dark Theme Colors (Techno-Spiritual)
val md_theme_dark_primary = Color(0xFF1A8068)
val md_theme_dark_onPrimary = Color(0xFF00382B)
val md_theme_dark_primaryContainer = Color(0xFF0D4038)
val md_theme_dark_onPrimaryContainer = Color(0xFF8FF7D7)
val md_theme_dark_secondary = Color(0xFFD2A84A)
val md_theme_dark_onSecondary = Color(0xFF402D00)
val md_theme_dark_secondaryContainer = Color(0xFF5C4200)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE0A9)
val md_theme_dark_tertiary = Color(0xFF55D6C2)
val md_theme_dark_onTertiary = Color(0xFF003732)
val md_theme_dark_tertiaryContainer = Color(0xFF005049)
val md_theme_dark_onTertiaryContainer = Color(0xFF75F3DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0A1113)
val md_theme_dark_onBackground = Color(0xFFEAF4F0)
val md_theme_dark_surface = Color(0xFF101A1B)
val md_theme_dark_onSurface = Color(0xFFEAF4F0)
val md_theme_dark_surfaceVariant = Color(0xFF172728)
val md_theme_dark_onSurfaceVariant = Color(0xFFA4B8B2)
val md_theme_dark_outline = Color(0xFFA4B8B2)

// Semantic State Colors
val siraj_light_success = Color(0xFF1B5E20)
val siraj_light_onSuccess = Color(0xFFFFFFFF)
val siraj_light_warning = Color(0xFFE65100)
val siraj_light_onWarning = Color(0xFFFFFFFF)
val siraj_light_processing = Color(0xFF0D47A1)
val siraj_light_onProcessing = Color(0xFFFFFFFF)

val siraj_dark_success = Color(0xFF4CAF50)
val siraj_dark_onSuccess = Color(0xFF003300)
val siraj_dark_warning = Color(0xFFFFC107)
val siraj_dark_onWarning = Color(0xFF4D3300)
val siraj_dark_processing = Color(0xFF64B5F6)
val siraj_dark_onProcessing = Color(0xFF002266)
